### ISSUE TITLE
Update "with-openssl-1.1.x" image to build from source

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/shared-docker#9]
There are two problems with using the alpine openssl 1.1.x package:

- The version can change out from underneath us
- It doesn't necessarily have all the algos we need to test against turned on.

For CI purposes, we should be building from source so that all the algos we need are guaranteed to be on.

We should be using a multistage build for this and copying the built library over into the image. To verify that the image is good when we set up the dockerfiles, we should manually do a ponylang/crypto clone and make test run to verify it all works as expected.

**Comment by damon-kwok** [comment]
```bash
git clone https://github.com/openssl/openssl.git --depth=1
cd openssl

output=$HOME/ssl
#  for gcc
./Configure linux-x86-64 zlib rc5 no-shared –api=1.1.1 --prefix=$output --openssldir=$output
# for clang
./Configure linux-x86-64-clang zlib rc5 no-shared  –api=1.1.1 --prefix=$output --openssldir=$output
```
make
```

**Comment by damon-kwok** [comment]
Now, we got: `libcrypto.a` `libssl.a`.
But， I’m thinking why we do not use `3.0.0`. Our static link library will not interfere with the dynamic library of OS.

**Comment by SeanTAllen** [comment]
Why do you say it won't interfere with the dynamic library?  @damon-kwok 

None of what you have here is usable in the image for CI. This is about the CI image, not anything larger. If you want to discuss something outside of the scope of this image, let's do that elsewhere so this can be focused on the issue.

**Comment by SeanTAllen** [comment]
I pushed a test of this and tried out with crypto and got a segfault so... not so good so far...

https://github.com/ponylang/crypto/pull/43/checks?check_run_id=986060565

**Comment by SeanTAllen** [comment]
Here's the docker file. It's working with latest ponyc release.

If anyone want to try and get a build of openssl that works correctly without sefgaulting on the ponylang/crypto unit tests.

```
ARG FROM_TAG=release
FROM ponylang/shared-docker-ci-x86-64-unknown-linux-builder:${FROM_TAG}

RUN apk update \
  && apk upgrade \
  && apk add --update \
  clang-dev \
  linux-headers \
  perl

RUN cd /tmp && \
  git clone https://github.com/openssl/openssl.git --depth=1 && \
  cd openssl && \
  ./Configure --api=1.1.1 no-shared enable-rc5 enable-md2 && \
  make install_sw && \
  cd /tmp && \
  rm -rf openssl
```

**Comment by SeanTAllen** [comment]
Ok, I have this working in a test.

**Comment by SeanTAllen** [comment]
PR has been opened for this.
